---
- name: Deploy to Tomcat
  hosts: web
  become: yes
  tasks:
    - name: Copy WAR file to Tomcat
      copy:
        src: "/var/snap/jenkins/4870/workspace/AM01/target/AM01.war"
        dest: "/opt/tomcat/webapps/AM01.war"
        owner: root
        group: root
        mode: '0644'
        remote_src: no

    - name: Reload systemd to apply changes
      command: systemctl daemon-reload
        

    - name: Restart Tomcat
      systemd:
        name: tomcat
        state: restarted
